import {
  MEETING_CATEGORY_OPTIONS,
  MEETING_CLASSIFICATION_OPTIONS,
  CONFIDENTIALITY_OPTIONS,
  MEETING_TYPE_OPTIONS,
  MEETING_NATURE_OPTIONS,
  MEETING_CHANNEL_OPTIONS,
  SECTOR_OPTIONS,
  MEETING_GOALS_COLUMNS,
  MEETING_AGENDA_COLUMNS,
  MINISTER_SUPPORT_COLUMNS,
  PREVIOUS_MEETING_COLUMNS,
  RELATED_DIRECTIVES_COLUMNS,
} from '../utils/constants';

export {
  MEETING_CATEGORY_OPTIONS,
  MEETING_CLASSIFICATION_OPTIONS,
  CONFIDENTIALITY_OPTIONS,
  MEETING_TYPE_OPTIONS,
  MEETING_NATURE_OPTIONS,
  MEETING_CHANNEL_OPTIONS,
  SECTOR_OPTIONS,
  MEETING_GOALS_COLUMNS,
  MEETING_AGENDA_COLUMNS,
  MINISTER_SUPPORT_COLUMNS,
  PREVIOUS_MEETING_COLUMNS,
  RELATED_DIRECTIVES_COLUMNS,
};

export const STEP1_TABS = [
  { id: 'meeting-info' as const, label: 'معلومات الاجتماع' },
  { id: 'other-sections' as const, label: 'باقي الأقسام' },
];

export const STEP1_ASYNC_SELECT_PAGE_SIZE = 10;

export const SUBMITTER_ROLE_CODE = 'SUBMITTER';
